config/routes.rb
Rails.application.routes.draw do

root 'billboards#index' 

resources :billboards do
  resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billboard.rb
class Billboard < ApplicationRecord
    has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :billboard, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  def index
    @billboards = Billboard.all
  end

  def show
    @billboard = Billboard.find(params[:id])
  end

  def new
    @billboard = Billboard.new
  end

  def edit
    @billboard = Billboard.find(params[:id])
  end

  def create
    @billboard = Billboard.new(billboard_params)

      if @billboard.save
        redirect_to billboards_path
      else
        render :new
      end
  end

def update
  @billboard = Billboard.find(params[:id])

    if @billboard.update(billboard_params)
        redirect_to billboards_path
    else
      render :edit
    end
end


  def destroy
    @billboard = Billboard.find(params[:id])
    @billboard.destroy
    redirect_to billboards_path
  end

  

  private

  def billboard_params
    params.require(:billboard).permit(:title, :description)
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @billboard = Billboard.find(params[:billboard_id])
    @songs = @billboard.songs
  end

  def show
    @billboard = Billboard.find(params[:billboard_id])
    @song = @billboard.song.find(params[:id])
  end

  def new
    @billboard = Billboard.find(params[:billboard_id])
    @song = @billboard.songs.new
  end

  def edit
    @billboard = Billboard.find(params[:billboard_id])
    @song = @billboard.song.find(params[:id])
  end

  def create
    @billboard = Billboard.find(params[:billboard_id])
    @song = @billboard.song.new(song_params)

      if @song.save
        redirect_to billboard_song_path
      else
        render :new
      end
  end

  def update
    @billboard = Billboard.find(params[:billboard_id])
    @song = @billboard.song.find(params[:id])
      if @song.update(song_params)
          redirect_to songs_path
      else
        render :edit
      end
  end


  def destroy
    @billboard = Billboard.find(params[:billboard_id])
    @song = @billboard.song.find(params[:id])
    @song.destroy
    redirect_to songs_path
  end

private

  def song_params
    params.require(:song).permit(:song_title, :song_artist)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/billboards/edit.html.erb
<h1>Update the billboard</h1>

<%= form_for @billboard do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<br />

<%=f.label :description %>
<%=f.text_field :description %>
<br />
<%= f.submit %>
<% end %>

app/views/billboards/index.html.erb
<h1>Top song billboards by region</h1>
<h4><%= link_to 'Add a new billboard', new_billboard_path %></h4>
<% @billboards.each do |billboard| %>
<h2> <%= billboard.title %></h2>
<h4><%= billboard.description %></h4>
<p><%= link_to 'Show me the top songs!', billboard_songs_path(billboard) %>
<%= link_to 'Update this billboard', edit_billboard_path(billboard) %>
<%= link_to 'Remove this billboard', billboard, method: :delete %> </p>
<% end %>

app/views/billboards/new.html.erb
<h1>Add a new regional billboard</h1>
<%= form_for @billboard do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<br />

<%=f.label :description %>
<%=f.text_field :description %>
<br />
<%= f.submit %>
<% end %>

app/views/billboards/show.html.erb
<h1><%= @billboard.title %></h1>
<%= link_to 'Back to the Billboards list', billboards_path %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hot100</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Update a Song</h1>
<%= form_for @song do |f| %>
<%= f.label :song_title %>
<%= f.text_field :song_title %>
<br />

<%=f.label :song_artist %>
<%=f.text_field :song_artist %>
<br />
<%= f.submit %>
<% end %>

app/views/songs/index.html.erb
<h1>Top Songs</h2>
<% @songs.each do |song| %>
<h3>Title: <%= @song.title %></h3>
<h5>Artist: <%= @song.artist %></h5>
<p><%= link_to 'Update Title or Artist', edit_song_path(song) %>
<%= link_to 'Remove Song', song, method: :delete %></p>
<% end %>
<%= link_to 'Add Song', new_billboard_song_path(params[:billboard_id]) %>

app/views/songs/new.html.erb
<h1>Add a song</h1>

<%= form_for @song do |f| %>
<%= f.label :song_title %>
<%= f.text_field :song_title %>
<br />

<%=f.label :song_artist %>
<%=f.text_field :song_artist %>
<br />
<%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>